################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_adc.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_adc_ex.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_cortex.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_crc.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_crc_ex.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash_ex.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_gpio.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c_ex.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pcd.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pcd_ex.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr_ex.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc_ex.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rtc.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rtc_ex.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_spi.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_spi_ex.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim_ex.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_uart.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_uart_ex.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_usb.c 

OBJS += \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_adc.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_adc_ex.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_cortex.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_crc.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_crc_ex.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_dma.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_flash.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_flash_ex.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_gpio.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_i2c.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_i2c_ex.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pcd.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pcd_ex.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pwr.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pwr_ex.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rcc.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rcc_ex.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rtc.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rtc_ex.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_spi.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_spi_ex.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_tim.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_tim_ex.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_uart.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_uart_ex.o \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_ll_usb.o 

C_DEPS += \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_adc.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_adc_ex.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_cortex.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_crc.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_crc_ex.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_dma.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_flash.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_flash_ex.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_gpio.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_i2c.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_i2c_ex.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pcd.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pcd_ex.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pwr.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pwr_ex.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rcc.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rcc_ex.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rtc.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rtc_ex.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_spi.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_spi_ex.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_tim.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_tim_ex.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_uart.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_uart_ex.d \
./Drivers/STM32L4xx_HAL_Driver/stm32l4xx_ll_usb.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_adc.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_adc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_adc_ex.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_adc_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_cortex.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_cortex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_crc.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_crc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_crc_ex.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_crc_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_dma.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_flash.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_flash_ex.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_gpio.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_gpio.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_i2c.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_i2c_ex.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pcd.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pcd.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pcd_ex.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pcd_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pwr.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_pwr_ex.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rcc.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rcc_ex.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rtc.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rtc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_rtc_ex.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rtc_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_spi.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_spi.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_spi_ex.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_spi_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_tim.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_tim_ex.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_uart.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_uart.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_hal_uart_ex.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_uart_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L4xx_HAL_Driver/stm32l4xx_ll_usb.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_usb.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


