################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_HWC_q7_fast_nonsquare.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_basic.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_fast.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_fast_nonsquare.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_RGB.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_basic.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_basic_nonsquare.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_fast.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_fast_nonsquare.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7_nonsquare.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_q7_q15.c \
/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_q7_q15_reordered.c 

OBJS += \
./CMSIS/NN/ConvolutionFunctions/arm_convolve_1x1_HWC_q7_fast_nonsquare.o \
./CMSIS/NN/ConvolutionFunctions/arm_convolve_HWC_q15_basic.o \
./CMSIS/NN/ConvolutionFunctions/arm_convolve_HWC_q15_fast.o \
./CMSIS/NN/ConvolutionFunctions/arm_convolve_HWC_q15_fast_nonsquare.o \
./CMSIS/NN/ConvolutionFunctions/arm_convolve_HWC_q7_RGB.o \
./CMSIS/NN/ConvolutionFunctions/arm_convolve_HWC_q7_basic.o \
./CMSIS/NN/ConvolutionFunctions/arm_convolve_HWC_q7_basic_nonsquare.o \
./CMSIS/NN/ConvolutionFunctions/arm_convolve_HWC_q7_fast.o \
./CMSIS/NN/ConvolutionFunctions/arm_convolve_HWC_q7_fast_nonsquare.o \
./CMSIS/NN/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7.o \
./CMSIS/NN/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7_nonsquare.o \
./CMSIS/NN/ConvolutionFunctions/arm_nn_mat_mult_kernel_q7_q15.o \
./CMSIS/NN/ConvolutionFunctions/arm_nn_mat_mult_kernel_q7_q15_reordered.o 

C_DEPS += \
./CMSIS/NN/ConvolutionFunctions/arm_convolve_1x1_HWC_q7_fast_nonsquare.d \
./CMSIS/NN/ConvolutionFunctions/arm_convolve_HWC_q15_basic.d \
./CMSIS/NN/ConvolutionFunctions/arm_convolve_HWC_q15_fast.d \
./CMSIS/NN/ConvolutionFunctions/arm_convolve_HWC_q15_fast_nonsquare.d \
./CMSIS/NN/ConvolutionFunctions/arm_convolve_HWC_q7_RGB.d \
./CMSIS/NN/ConvolutionFunctions/arm_convolve_HWC_q7_basic.d \
./CMSIS/NN/ConvolutionFunctions/arm_convolve_HWC_q7_basic_nonsquare.d \
./CMSIS/NN/ConvolutionFunctions/arm_convolve_HWC_q7_fast.d \
./CMSIS/NN/ConvolutionFunctions/arm_convolve_HWC_q7_fast_nonsquare.d \
./CMSIS/NN/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7.d \
./CMSIS/NN/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7_nonsquare.d \
./CMSIS/NN/ConvolutionFunctions/arm_nn_mat_mult_kernel_q7_q15.d \
./CMSIS/NN/ConvolutionFunctions/arm_nn_mat_mult_kernel_q7_q15_reordered.d 


# Each subdirectory must supply rules for building sources it contributes
CMSIS/NN/ConvolutionFunctions/arm_convolve_1x1_HWC_q7_fast_nonsquare.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_HWC_q7_fast_nonsquare.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

CMSIS/NN/ConvolutionFunctions/arm_convolve_HWC_q15_basic.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_basic.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

CMSIS/NN/ConvolutionFunctions/arm_convolve_HWC_q15_fast.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_fast.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

CMSIS/NN/ConvolutionFunctions/arm_convolve_HWC_q15_fast_nonsquare.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_fast_nonsquare.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

CMSIS/NN/ConvolutionFunctions/arm_convolve_HWC_q7_RGB.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_RGB.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

CMSIS/NN/ConvolutionFunctions/arm_convolve_HWC_q7_basic.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_basic.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

CMSIS/NN/ConvolutionFunctions/arm_convolve_HWC_q7_basic_nonsquare.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_basic_nonsquare.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

CMSIS/NN/ConvolutionFunctions/arm_convolve_HWC_q7_fast.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_fast.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

CMSIS/NN/ConvolutionFunctions/arm_convolve_HWC_q7_fast_nonsquare.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_fast_nonsquare.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

CMSIS/NN/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

CMSIS/NN/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7_nonsquare.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7_nonsquare.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

CMSIS/NN/ConvolutionFunctions/arm_nn_mat_mult_kernel_q7_q15.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_q7_q15.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

CMSIS/NN/ConvolutionFunctions/arm_nn_mat_mult_kernel_q7_q15_reordered.o: /home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_q7_q15_reordered.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32_SENSORTILE -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DARM_MATH_CM4 -D__DSP_PRESENT -D__FPU_PRESENT -I../../../../../../../Cifar-10/code/m4 -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/SensorTile" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/Common" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/hts221" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Projects/SensorTile/Applications/DataLog/Inc" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FatFs/src/drivers" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Middlewares/Third_Party/FreeRTOS/Source/include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/Drivers/BSP/Components/stc3115" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/NN/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/DSP/Include" -I"/home/matteo/Documents/projects/sensortile/insieme-on-stm32l4/CMSIS/Core/Include"  -O3 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


